apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-atlas-registration
  labels:
    related-to: dbaas-operator
    type: dbaas-provider-registration
data:
  provider: MongoDBAtlas
  inventory_kind: MongoDBAtlasInventory
  connection_kind: MongoDBAtlasConnection
  credentials_fields: |
    - key: orgId
      display_name: Organization ID
      type: string
      required: true
    - key: publicApiKey
      display_name: Public API Key
      type: string
      required: true
    - key: privateApiKey
      display_name: Private API Key
      type: maskedstring
      required: true
    